//! The keyboard map in `docs/user-guide.md` is generated from the binding table, so the
//! documentation cannot drift from the keys the app actually has. On a mismatch the test
//! fails; `AC2_BLESS=1 cargo test -p ac2-ui --test keymap_doc` rewrites the section.

use std::path::PathBuf;

use ac2_ui::keys::{CommandId, Keymap, LabelStyle, Scope};

const BEGIN: &str = "<!-- keymap:begin (generated by crates/ac2-ui/tests/keymap_doc.rs) -->";
const END: &str = "<!-- keymap:end -->";

fn cell(s: &str) -> String {
    s.replace('|', "\\|")
}

fn render() -> String {
    let km = Keymap::default();
    let mut out = String::new();
    out.push_str(
        "Keys as on Linux and Windows; on macOS `Ctrl` is `⌘` and `Alt` is `⌥`. Every \
         binding can be changed in `keys.toml` using the names in the last column.\n",
    );
    for scope in Scope::ALL {
        let mut rows = Vec::new();
        for &c in CommandId::ALL {
            let chords = km.chords(c, scope);
            if chords.is_empty() {
                continue;
            }
            let keys = chords
                .iter()
                .map(|ch| format!("`{}`", cell(&ch.label_in(LabelStyle::Pc))))
                .collect::<Vec<_>>()
                .join(" or ");
            rows.push(format!("| {keys} | {} | `{}` |", cell(c.title()), c.name()));
        }
        if rows.is_empty() {
            continue;
        }
        out.push_str(&format!(
            "\n#### {}\n\n| Keys | Command | `keys.toml` |\n|---|---|---|\n",
            scope.title()
        ));
        for r in rows {
            out.push_str(&r);
            out.push('\n');
        }
    }
    let unbound: Vec<CommandId> = CommandId::ALL
        .iter()
        .copied()
        .filter(|c| Scope::ALL.iter().all(|s| km.chords(*c, *s).is_empty()))
        .collect();
    if !unbound.is_empty() {
        out.push_str(
            "\n#### Command palette only (`Ctrl+K`)\n\n| Command | `keys.toml` |\n|---|---|\n",
        );
        for c in unbound {
            out.push_str(&format!("| {} | `{}` |\n", cell(c.title()), c.name()));
        }
    }
    out
}

#[test]
fn user_guide_keymap_matches_binding_table() {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../docs/user-guide.md");
    let doc = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    let doc = doc.replace("\r\n", "\n");
    let (Some(b), Some(e)) = (doc.find(BEGIN), doc.find(END)) else {
        panic!("{} lacks the keymap markers", path.display());
    };
    let start = b + BEGIN.len();
    let current = &doc[start..e];
    let want = format!("\n{}\n", render());
    if current == want {
        return;
    }
    if std::env::var("AC2_BLESS").is_ok_and(|v| v == "1") {
        let new = format!("{}{want}{}", &doc[..start], &doc[e..]);
        std::fs::write(&path, new).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
        return;
    }
    panic!(
        "the keyboard map in docs/user-guide.md is out of date; regenerate it with\n  \
         AC2_BLESS=1 cargo test -p ac2-ui --test keymap_doc"
    );
}
