"""`python -m crosscheck comparison`: the results tables of `comparison.md`, rebuilt from the
committed baselines. The prose around them is hand-written; only the part between the two
marker comments is replaced, so a baseline update and its tables land in one commit.

The tables show the current state: per rig and stage only the newest baseline (by run time),
since an older one at another level was taken on an older ac2 build. A rig baseline holds
hundreds of checks; the tables keep the rows that say how far ac2 can be trusted against REW
and against the analytic truths (steady sines, direct cross-spectra), each cell the worst
judged value of its checks with where it was and the verdict counts."""
from __future__ import annotations

import json
import re
from pathlib import Path

from .baseline import BASELINES, HOST_DIR, JUDGED

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "comparison.md"
BEGIN = "<!-- BEGIN generated by `python -m crosscheck comparison` from baselines/: do not edit by hand -->"
END = "<!-- END generated -->"
STATUSES = ("FAIL", "WARN", "PASS", "INCONCLUSIVE", "INFO")

# (row label, pattern on the key without its stage prefix[, statistic]). A named group `o` (the
# harmonic order) is shown with the location. Sweeps: the stage's main sweep (10 Hz on the
# electrical path, 20 Hz on the speaker), so one row reads one ac2 analysis.
#
# The statistic says what a value's sign means. SIGNED (the default): a − b, the sign is the
# direction. ABS: a magnitude with no direction (a band pair's larger of |mean difference| and
# its spread about that mean), shown unsigned so it does not read as a bias. SHARE: a fraction.
SIGNED, ABS, SHARE = "signed", "abs", "share"
COUNT_UNITS = ("columns", "bins")
_SWEEP = r"ac2 sweep (?:10|20)Hz-5\.5s"
RIG_ROWS: list[tuple[str, str] | tuple[str, str, str]] = [
    ("ac2 sweep vs REW offline import, magnitude spread per band", rf"mag\.{_SWEEP}\|REW offline\.", ABS),
    ("ac2 sweep vs REW offline import, phase, max(\\|mean\\|, spread) per band", rf"phase\.{_SWEEP}\|REW offline\.", ABS),
    ("REW offline vs direct (same recording), magnitude, max(\\|mean\\|, spread) per band",
     r"mag\.REW offline\|direct \(REW recording\)\.", ABS),
    ("REW offline vs direct (same recording), phase, max(\\|mean\\|, spread) per band",
     r"phase\.REW offline\|direct \(REW recording\)\.", ABS),
    ("ac2 sweep vs direct (its own capture), magnitude, max(\\|mean\\|, spread) per band",
     rf"mag\.{_SWEEP}\|direct \(ac2 capture [^)]*\)\.", ABS),
    ("ac2 sweep vs direct (its own capture), phase, max(\\|mean\\|, spread) per band",
     rf"phase\.{_SWEEP}\|direct \(ac2 capture [^)]*\)\.", ABS),
    ("ac2 live TF vs direct (γ² ≥ 0.99), magnitude, max(\\|mean\\|, spread) per band",
     r"mag\.ac2 TF\|direct \(TF capture\)\.", ABS),
    ("ac2 live TF vs direct (γ² ≥ 0.99), phase, max(\\|mean\\|, spread) per band",
     r"phase\.ac2 TF\|direct \(TF capture\)\.", ABS),
    ("ac2 sweep vs steady sine, magnitude", rf"sine_mag\.{_SWEEP}@"),
    ("REW offline vs steady sine, magnitude", r"sine_mag\.REW offline@"),
    ("ac2 live TF vs steady sine, magnitude", r"sine_mag\.ac2 TF@"),
    ("ac2 sweep vs steady sine, phase", rf"sine_phase\.{_SWEEP}@"),
    ("REW offline vs steady sine, phase", r"sine_phase\.REW offline@"),
    ("ac2 live TF vs steady sine, phase", r"sine_phase\.ac2 TF@"),
    ("ac2 meas÷ref vs REW (meas − ref), absolute level", r"level\.ac2_vs_rew_meas_minus_ref$"),
    ("ac2 reference level vs REW's", r"level\.ac2_ref_vs_rew_ref$"),
    ("ac2 reported arrival vs direct, every sweep", r"delay\.ac2_arrival\."),
    ("ac2 arrival + phase slope vs direct, every sweep", r"delay\.ac2_total\."),
    ("group delay vs sine pairs: ac2, ±1/12-oct fit", r"gd\.ac2 ±1/12-oct fit@"),
    ("group delay vs sine pairs: ac2 as displayed", r"gd\.ac2 as displayed \(central difference\)@"),
    ("group delay vs sine pairs: REW, ±1/12-oct fit", r"gd\.REW offline import ±1/12-oct fit@"),
    ("group delay vs sine pairs: REW's own GD export", r"gd\.REW offline import own GD export \(±1/12-oct mean\)@"),
    ("H2–H5 vs steady sine: ac2 sweep", rf"(?P<o>h[2-5])\.{_SWEEP}@"),
    ("H2–H5 vs steady sine: REW offline import", r"(?P<o>h[2-5])\.REW offline import@"),
    ("absolute SPL vs steady sine: ac2 sweep", r"spl\.ac2 sweep@"),
    ("absolute SPL vs steady sine: REW (cal from ac2)", r"spl\.REW \(SPL, cal from ac2\)@"),
    ("live TF: share of columns at γ² ≥ 0.99, 31 Hz–20 kHz", r"coherence\.tf$", SHARE),
]
AMBIENT_ROWS: list[tuple[str, str]] = [
    ("LZeq ac2 vs numpy", r"leq\.Z\.ac2$"),
    ("LAeq ac2 vs numpy", r"leq\.A\.ac2$"),
    ("LCeq ac2 vs numpy", r"leq\.C\.ac2$"),
    ("LAeq REW vs numpy", r"leq\.A\.REW$"),
    ("LAeq ac2 vs REW", r"leq\.A\.ac2_rew$"),
    ("1/3-oct bands 25 Hz–16 kHz: ac2 RTA vs numpy, largest \\|difference\\|", r"bands\.ac2 RTA$", ABS),
    ("1/3-oct bands 25 Hz–16 kHz: REW RTA vs numpy, largest \\|difference\\|", r"bands\.REW RTA$", ABS),
    ("1/3-oct bands: ac2 RTA vs its own filters' response applied to the recording, worst band",
     r"bands\.ac2 RTA\|own filters$"),
]
# Distortion coverage: per harmonic order and analyser, how many tones were judged at all.
HARMONIC_ROWS: list[tuple[str, str]] = [
    (f"H{k} {who}", rf"h{k}\.{pat}@") for who, pat in (("ac2 sweep", _SWEEP), ("REW offline import", r"REW offline import"))
    for k in range(2, 6)]
# OSM stage: (column header, check slug after `osm.<case>.`)
# (column header, check slug after `osm.<case>.`[, statistic]); see SIGNED/ABS above
OSM_TF_COLS = [
    ("\\|ac2 \\|H\\| − truth\\|, dB", "ac2_tf_h_vs_analytic", ABS),
    ("\\|OSM \\|H\\| − truth\\|, dB", "osm_m_r_vs_analytic", ABS),
    ("\\|ac2 ∠ − truth\\|, °", "ac2_tf_phase_vs_analytic", ABS),
    ("\\|OSM ∠ − truth\\|, °", "osm_phase_vs_analytic", ABS),
    ("\\|ac2 − OSM\\| on \\|H\\|, dB", "ac2_vs_osm_h", ABS),
    ("\\|ac2 − OSM\\| on ∠, °", "ac2_vs_osm_phase", ABS),
    ("ac2 γ² − true γ² (mean)", "ac2_γ²_vs_true_γ²"),
    ("ac2 γ² − E[γ̂²] (mean)", "ac2_γ²_vs_its_expected_value"),
    ("OSM γ² − E[γ̂²] (mean)", "osm_γ²_vs_its_expected_value"),
]
# Rig takes and masks: how many columns each OSM comparison stands on, and the tails a median hides
OSM_COVERAGE_COLS = [
    ("columns judged", "columns_judged"),
    ("below the γ² gate", "masked_columns_below_the_coherence_gate"),
    ("ac2 non-finite", "masked_ac2_non_finite_columns"),
    ("OSM bins under its float32 floor", "masked_osm_bins_below_the_reference_floor"),
    ("OSM NaN-phase bins", "masked_osm_nan_phase_bins"),
    ("\\|ac2 − OSM\\| on \\|H\\|: 95th pct, dB", "ac2_vs_osm_h_95th_percentile_difference", ABS),
    ("\\|ac2 − OSM\\| on \\|H\\|: max, dB", ("ac2_vs_osm_h_max_difference", "ac2_vs_osm_h_max_difference_frequency")),
    ("\\|ac2 − OSM\\| on ∠: 95th pct, °", "ac2_vs_osm_phase_95th_percentile_difference", ABS),
    ("\\|ac2 − OSM\\| on ∠: max, °", ("ac2_vs_osm_phase_max_difference", "ac2_vs_osm_phase_max_difference_frequency")),
]
OSM_OTHER_COLS = [
    ("ac2 finder − truth", "ac2_delay_finder_vs_analytic"),
    ("OSM finder − truth", "osm_delay_finder_vs_analytic"),
    ("ac2 slope − truth", "ac2_phase_slope_vs_analytic"),
    ("OSM slope − truth", "osm_phase_slope_vs_analytic"),
    ("ac2 − OSM finder", "ac2_delay_finder_vs_osm_s"),
    ("ac2 H1 in noise − 0 dB (median), dB", "ac2_h1_h_vs_analytic_0_db"),
    ("OSM mean ratio − E\\|1+N/R\\|, dB", "osm_mean_m_r_vs_its_expected_bias"),
    ("ac2 spectrum − truth, dB", "ac2_spectrum"),
    ("OSM spectrum (converted) − truth, dB", ("osm_module_3_01", "osm_module_3_01_db_vs_analytic")),
]


# ------------------------------------------------------------------ formatting
def fmt_value(v: float | None, unit: str, stat: str = SIGNED) -> str:
    if v is None:
        return "—"
    if unit in COUNT_UNITS:
        return f"{v:.0f}"
    if stat == SHARE:
        return f"{v * 100:.1f} %"
    if unit == "rel":
        s = f"{v * 100:+.1f} %"
    elif unit == "µs":
        s = f"{v:+.2f} µs"
    else:
        s = f"{v:+.3f}" + (f" {unit}" if unit and unit != "°" else unit)
    # a value that rounds to zero, or a magnitude without a direction, carries no sign
    s = re.sub(r"^[+-](0\.0+(?:\D|$))", r"\1", s)
    if stat == ABS:
        s = s.lstrip("+-")
    return s.replace("-", "−", 1) if s.startswith("-") else s


def _loc(rest: str, order: str | None) -> str:
    """Where in the stage a check sits: a band, a tone, a sweep."""
    m = re.fullmatch(r"(\d+(?:\.\d+)?)-(\d+(?:\.\d+)?)", rest)
    if m:
        rest = f"{m.group(1)}–{m.group(2)} Hz"
    else:
        rest = re.sub(r"^(\d+(?:\.\d+)?)Hz$", r"\1 Hz", rest)
    return f"{order.upper()} {rest}" if order else rest


def counts_text(entries: list[dict]) -> str:
    c = {}
    for e in entries:
        c[e["status"]] = c.get(e["status"], 0) + 1
    return ", ".join(f"{s} {c[s]}" for s in STATUSES if c.get(s))


def cell(matches: list[tuple[str, str | None, dict]], stat: str = SIGNED) -> str:
    """The worst judged value per unit (with where), then the verdict counts. Without a judged
    value, the largest INFO value or just the counts (an INCONCLUSIVE value is a bound)."""
    if not matches:
        return "—"
    entries = [e for _, _, e in matches]
    parts = []
    for unit in dict.fromkeys(e.get("unit") or "" for e in entries):
        mine = [(r, o, e) for r, o, e in matches if (e.get("unit") or "") == unit and e["value"] is not None]
        judged = [m for m in mine if m[2]["status"] in JUDGED] or [m for m in mine if m[2]["status"] == "INFO"]
        if not judged:
            continue
        r, o, e = max(judged, key=lambda m: abs(m[2]["value"]))
        where = _loc(r, o) if len(matches) > 1 and r else ""
        # an unsigned band statistic hides its direction: the signed mean beside it gives it back
        extra = [f"mean {fmt_value(e['mean'], unit)}"] if stat == ABS and e.get("mean") is not None else []
        extra += [f"n {e['n']:.0f}"] if e.get("n") is not None else []
        parts.append(fmt_value(e["value"], unit, stat) + (f" @ {where}" if where else "")
                     + (f" [{', '.join(extra)}]" if extra else ""))
    head = "; ".join(parts)
    return (f"{head} ({counts_text(entries)})" if head else counts_text(entries))


# ------------------------------------------------------------------ tables
def load(root: Path) -> list[tuple[Path, dict]]:
    return [(p, json.loads(p.read_text())) for p in sorted(Path(root).glob("*/*.json"))]


def _level(b: dict) -> str:
    return "silent" if b.get("level_dbfs") is None else f"{b['level_dbfs']:g} dBFS".replace("-", "−")


def _short_build(s: str | None) -> str:
    m = re.search(r"\+([0-9a-f]{7})", s or "")
    return m.group(1) if m else (s or "—")


def _run(b: dict) -> str:
    return (b.get("provenance") or {}).get("run") or ""


def _ppo(b: dict) -> int | None:
    """Columns per octave of a rig path baseline; 48 when not recorded (ac2's default)."""
    return None if b["stage"] in ("osm", "ambient") else int(b.get("resolution_ppo") or 48)


def newest(items: list[tuple[Path, dict]]) -> list[tuple[Path, dict]]:
    """The newest baseline per (rig, stage, resolution), in file order: a take at another column
    width measures a different quantity, so it stands beside the default one, not over it."""
    best: dict[tuple, tuple[Path, dict]] = {}
    for p, b in items:
        k = (p.parent.name, b["stage"], _ppo(b))
        if k not in best or _run(b) > _run(best[k][1]):
            best[k] = (p, b)
    return [pb for pb in items if pb in best.values()]


def heading(b: dict) -> str:
    pv = b.get("provenance") or {}
    res = f" 1/{_ppo(b)} oct" if _ppo(b) not in (None, 48) else ""
    return f"{b['stage']} {_level(b)}{res} ({pv.get('run')}, ac2 {_short_build(pv.get('ac2_build'))})"


def counts_line(b: dict) -> str:
    s = b.get("summary") or {}
    return ", ".join(f"{k} {s[k]}" for k in STATUSES if s.get(k))


def matches_for(b: dict, pattern: str) -> list[tuple[str, str | None, dict]]:
    rx = re.compile(pattern)
    out = []
    for k, e in b["checks"].items():
        k2 = k.split(".", 1)[1] if "." in k else k
        m = rx.match(k2)
        if m:
            out.append((k2[m.end():], m.groupdict().get("o"), e))
    return out


def rig_table(bs: list[dict], rows: list[tuple[str, ...]], verdicts: bool = True) -> list[str]:
    out = ["| check | " + " | ".join(heading(b) for b in bs) + " |", "|---|" + "---|" * len(bs)]
    if verdicts:
        out.append("| verdicts | " + " | ".join(counts_line(b) for b in bs) + " |")
    for label, pat, *stat in rows:
        cells = [cell(matches_for(b, pat), *stat) for b in bs]
        if all(c == "—" for c in cells):
            continue
        out.append(f"| {label} | " + " | ".join(cells) + " |")
    return out


def _osm_cell(b: dict, case: str, slug, stat: str = SIGNED) -> str:
    if isinstance(slug, tuple) and slug[1].endswith("_frequency"):  # a maximum and where it sits
        e, ef = (b["checks"].get(f"osm.{case}.{s}") for s in slug)
        if e is None:
            return ""
        return fmt_value(e["value"], "", ABS) + (f" @ {ef['value']:.1f} Hz" if ef and ef["value"] is not None else "")
    for s in (slug if isinstance(slug, tuple) else (slug,)):
        e = b["checks"].get(f"osm.{case}.{s}")
        if e is not None:
            # the column header carries the unit; a count is shown as one
            v = fmt_value(e["value"], e.get("unit") if e.get("unit") in COUNT_UNITS else "", stat)
            return v if e["status"] in ("PASS", "INFO") else f"{v} ({e['status']})"
    return ""


def osm_tables(b: dict) -> list[str]:
    seen = list(dict.fromkeys(k.split(".")[1] for k in b["checks"]))
    planned = ((b.get("provenance") or {}).get("flags") or {}).get("cases") or []
    cases = [c for c in planned if c in seen] + [c for c in seen if c not in planned]
    out = []
    for title, cols, median in (("Transfer: max over the gated columns; a rig take (not a planned fixture) "
                                 "shows the median over its columns", OSM_TF_COLS, " (median)"),
                                ("Delay (samples), noise and spectrum: signed", OSM_OTHER_COLS, ""),
                                ("Columns behind each comparison, and a rig take's tails", OSM_COVERAGE_COLS, "")):
        # a rig take has no truth: its ac2 − OSM transfer statistic is a median, so its row says so
        rows = [[c if c in planned else c + median] + [_osm_cell(b, c, *s) for _, *s in cols] for c in cases]
        rows = [r for r in rows if any(r[1:])]
        out += [f"**{title}**", "", "| case | " + " | ".join(h for h, *_ in cols) + " |",
                "|---|" + "---|" * len(cols)]
        out += ["| " + " | ".join(r) + " |" for r in rows] + [""]
    return out


def render(root: Path = BASELINES) -> str:
    items = newest(load(Path(root)))
    out = [BEGIN, ""]
    by_rig: dict[str, list[dict]] = {}
    for p, b in items:
        by_rig.setdefault(p.parent.name, []).append(b)
    for rig, bs in sorted(by_rig.items(), key=lambda kv: (kv[0] == HOST_DIR, kv[0])):
        for b in (b for b in bs if b["stage"] == "osm"):
            pv = b.get("provenance") or {}
            out += [f"### OSM stage ({pv.get('run')}, ac2 {_short_build(pv.get('ac2_build'))}, "
                    f"{pv.get('osm_version')}: {counts_line(b)})", ""] + osm_tables(b)
        paths = [b for b in bs if b["stage"] not in ("osm", "ambient")]
        if paths:
            paths.sort(key=lambda b: (b["stage"] != "xone", _ppo(b) != 48, _ppo(b)))
            out += [f"### {rig}: electrical (xone) and speaker (genelec) paths", ""] + rig_table(paths, RIG_ROWS) + [""]
            out += [f"### {rig}: distortion coverage per harmonic order (steady-sine tones judged)", ""]
            out += rig_table(paths, HARMONIC_ROWS, verdicts=False) + [""]
        for b in (b for b in bs if b["stage"] == "ambient"):
            out += [f"### {rig}: ambient", ""] + rig_table([b], AMBIENT_ROWS) + [""]
    out.append(END)
    return "\n".join(out) + "\n"


def splice(doc: str, generated: str) -> str:
    i, j = doc.find(BEGIN), doc.find(END)
    if i < 0 or j < i:
        raise ValueError(f"{DOC.name}: the marker comments are missing")
    return doc[:i] + generated + doc[j + len(END) + 1:]


def update(doc_path: Path = DOC, root: Path = BASELINES, check: bool = False) -> tuple[bool, Path]:
    """Rewrites the generated part; returns (it was current, path). `check` writes nothing."""
    doc = Path(doc_path).read_text()
    new = splice(doc, render(root))
    current = new == doc
    if not check and not current:
        Path(doc_path).write_text(new)
    return current, Path(doc_path)
