"""`python -m crosscheck comparison`: the results tables of `comparison.md`, rebuilt from the
committed baselines. The prose around them is hand-written; only the part between the two
marker comments is replaced, so a baseline update and its tables land in one commit.

A rig baseline holds hundreds of checks; the tables keep the rows that say how far ac2 can be
trusted against REW and against the analytic truths (steady sines, direct cross-spectra), each
cell the worst judged value of its checks with where it was and the verdict counts."""
from __future__ import annotations

import json
import re
from pathlib import Path

from .baseline import BASELINES, HOST_DIR, JUDGED

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "comparison.md"
BEGIN = "<!-- BEGIN generated by `python -m crosscheck comparison` from baselines/: do not edit by hand -->"
END = "<!-- END generated -->"
STATUSES = ("FAIL", "WARN", "PASS", "INCONCLUSIVE", "INFO")

# (row label, pattern on the key without its stage prefix). A named group `o` (the harmonic
# order) is shown with the location. Sweeps: the stage's main sweep (10 Hz on the electrical
# path, 20 Hz on the speaker), so one row reads one ac2 analysis.
_SWEEP = r"ac2 sweep (?:10|20)Hz-5\.5s"
RIG_ROWS: list[tuple[str, str]] = [
    ("ac2 sweep vs REW offline import, magnitude spread per band", rf"mag\.{_SWEEP}\|REW offline\."),
    ("ac2 sweep vs REW offline import, phase spread per band", rf"phase\.{_SWEEP}\|REW offline\."),
    ("REW offline vs direct (same recording), magnitude", r"mag\.REW offline\|direct \(REW recording\)\."),
    ("REW offline vs direct (same recording), phase", r"phase\.REW offline\|direct \(REW recording\)\."),
    ("ac2 sweep vs direct (its own capture), magnitude", rf"mag\.{_SWEEP}\|direct \(ac2 capture [^)]*\)\."),
    ("ac2 sweep vs direct (its own capture), phase", rf"phase\.{_SWEEP}\|direct \(ac2 capture [^)]*\)\."),
    ("ac2 live TF vs direct (γ² ≥ 0.99), magnitude", r"mag\.ac2 TF\|direct \(TF capture\)\."),
    ("ac2 live TF vs direct (γ² ≥ 0.99), phase", r"phase\.ac2 TF\|direct \(TF capture\)\."),
    ("ac2 sweep vs steady sine, magnitude", rf"sine_mag\.{_SWEEP}@"),
    ("REW offline vs steady sine, magnitude", r"sine_mag\.REW offline@"),
    ("ac2 live TF vs steady sine, magnitude", r"sine_mag\.ac2 TF@"),
    ("ac2 sweep vs steady sine, phase", rf"sine_phase\.{_SWEEP}@"),
    ("REW offline vs steady sine, phase", r"sine_phase\.REW offline@"),
    ("ac2 live TF vs steady sine, phase", r"sine_phase\.ac2 TF@"),
    ("ac2 meas÷ref vs REW (meas − ref), absolute level", r"level\.ac2_vs_rew_meas_minus_ref$"),
    ("ac2 reference level vs REW's", r"level\.ac2_ref_vs_rew_ref$"),
    ("ac2 reported arrival vs direct, every sweep", r"delay\.ac2_arrival\."),
    ("ac2 arrival + phase slope vs direct, every sweep", r"delay\.ac2_total\."),
    ("REW offline reported delay (removed by its timing markers)", r"delay\.rew\.REW offline import\.reported delay$"),
    ("group delay vs sine pairs: ac2, ±1/12-oct fit", r"gd\.ac2 ±1/12-oct fit@"),
    ("group delay vs sine pairs: ac2 as displayed", r"gd\.ac2 as displayed \(central difference\)@"),
    ("group delay vs sine pairs: REW, ±1/12-oct fit", r"gd\.REW offline import ±1/12-oct fit@"),
    ("group delay vs sine pairs: REW's own GD export", r"gd\.REW offline import own GD export \(±1/12-oct mean\)@"),
    ("H2–H5 vs steady sine: ac2 sweep", rf"(?P<o>h[2-5])\.{_SWEEP}@"),
    ("H2–H5 vs steady sine: REW offline import", r"(?P<o>h[2-5])\.REW offline import@"),
    ("absolute SPL vs steady sine: ac2 sweep", r"spl\.ac2 sweep@"),
    ("absolute SPL vs steady sine: REW (cal from ac2)", r"spl\.REW \(SPL, cal from ac2\)@"),
    ("live TF: share of columns at γ² ≥ 0.99", r"coherence\.tf$"),
]
AMBIENT_ROWS: list[tuple[str, str]] = [
    ("LZeq ac2 vs numpy", r"leq\.Z\.ac2$"),
    ("LAeq ac2 vs numpy", r"leq\.A\.ac2$"),
    ("LCeq ac2 vs numpy", r"leq\.C\.ac2$"),
    ("LAeq REW vs numpy", r"leq\.A\.REW$"),
    ("LAeq ac2 vs REW", r"leq\.A\.ac2_rew$"),
    ("1/3-oct bands: ac2 RTA vs numpy, worst band", r"bands\.ac2 RTA$"),
    ("1/3-oct bands: REW RTA vs numpy, worst band", r"bands\.REW RTA$"),
]
# OSM stage: (column header, check slug after `osm.<case>.`)
OSM_TF_COLS = [
    ("ac2 \\|H\\| − truth, dB", "ac2_tf_h_vs_analytic"),
    ("OSM \\|H\\| − truth, dB", "osm_m_r_vs_analytic"),
    ("ac2 ∠ − truth, °", "ac2_tf_phase_vs_analytic"),
    ("OSM ∠ − truth, °", "osm_phase_vs_analytic"),
    ("ac2 − OSM \\|H\\|, dB", "ac2_vs_osm_h"),
    ("ac2 − OSM ∠, °", "ac2_vs_osm_phase"),
    ("ac2 γ² − true γ²", "ac2_γ²_vs_true_γ²"),
    ("OSM γ² − E[γ̂²]", "osm_γ²_vs_its_expected_value"),
]
OSM_OTHER_COLS = [
    ("ac2 finder − truth", "ac2_delay_finder_vs_analytic"),
    ("OSM finder − truth", "osm_delay_finder_vs_analytic"),
    ("ac2 slope − truth", "ac2_phase_slope_vs_analytic"),
    ("OSM slope − truth", "osm_phase_slope_vs_analytic"),
    ("ac2 − OSM finder", "ac2_delay_finder_vs_osm_s"),
    ("ac2 H1 in noise − 0 dB, dB", "ac2_h1_h_vs_analytic_0_db"),
    ("OSM mean ratio − E\\|1+N/R\\|, dB", "osm_mean_m_r_vs_its_expected_bias"),
    ("ac2 spectrum − truth, dB", "ac2_spectrum"),
    ("OSM spectrum (converted) − truth, dB", ("osm_module_3_01", "osm_module_3_01_db_vs_analytic")),
]
OSM_INFO_PREFIX = "uncompensated_"
OSM_INFO_LABELS = {
    "ac2_h_vs_analytic": "ac2 |H| − truth, max over all columns, dB",
    "ac2_phase_vs_analytic": "ac2 ∠ − truth, max, °",
    "ac2_phase_slope_vs_analytic": "ac2 phase slope − truth, samples",
    "osm_m_r_vs_analytic": "OSM |M|/|R| − truth, max, dB",
    "osm_phase_vs_analytic": "OSM ∠ − truth, max, °",
    "ac2_h_vs_osm": "ac2 − OSM |H|, max over all columns, dB",
    "ac2_phase_vs_osm": "ac2 − OSM ∠, max, °",
}


# ------------------------------------------------------------------ formatting
def fmt_value(v: float | None, unit: str) -> str:
    if v is None:
        return "—"
    if unit == "rel":
        s = f"{v * 100:+.1f} %"
    elif unit == "µs":
        s = f"{v:+.2f} µs"
    else:
        s = f"{v:+.3f}" + (f" {unit}" if unit and unit != "°" else unit)
    # a value that rounds to zero carries no sign
    s = re.sub(r"^[+-](0\.0+(?:\D|$))", r"\1", s)
    return s.replace("-", "−", 1) if s.startswith("-") else s


def _loc(rest: str, order: str | None) -> str:
    """Where in the stage a check sits: a band, a tone, a sweep."""
    m = re.fullmatch(r"(\d+(?:\.\d+)?)-(\d+(?:\.\d+)?)", rest)
    if m:
        rest = f"{m.group(1)}–{m.group(2)} Hz"
    else:
        rest = re.sub(r"^(\d+(?:\.\d+)?)Hz$", r"\1 Hz", rest)
    return f"{order.upper()} {rest}" if order else rest


def counts_text(entries: list[dict]) -> str:
    c = {}
    for e in entries:
        c[e["status"]] = c.get(e["status"], 0) + 1
    return ", ".join(f"{s} {c[s]}" for s in STATUSES if c.get(s))


def cell(matches: list[tuple[str, str | None, dict]]) -> str:
    """The worst judged value per unit (with where), then the verdict counts. Without a judged
    value, the largest INFO value or just the counts (an INCONCLUSIVE value is a bound)."""
    if not matches:
        return "—"
    entries = [e for _, _, e in matches]
    parts = []
    for unit in dict.fromkeys(e.get("unit") or "" for e in entries):
        mine = [(r, o, e) for r, o, e in matches if (e.get("unit") or "") == unit and e["value"] is not None]
        judged = [m for m in mine if m[2]["status"] in JUDGED] or [m for m in mine if m[2]["status"] == "INFO"]
        if not judged:
            continue
        r, o, e = max(judged, key=lambda m: abs(m[2]["value"]))
        where = _loc(r, o) if len(matches) > 1 and r else ""
        parts.append(fmt_value(e["value"], unit) + (f" @ {where}" if where else ""))
    head = "; ".join(parts)
    return (f"{head} ({counts_text(entries)})" if head else counts_text(entries))


# ------------------------------------------------------------------ tables
def load(root: Path) -> list[tuple[Path, dict]]:
    return [(p, json.loads(p.read_text())) for p in sorted(Path(root).glob("*/*.json"))]


def _level(b: dict) -> str:
    return "silent" if b.get("level_dbfs") is None else f"{b['level_dbfs']:g} dBFS".replace("-", "−")


def _short_build(s: str | None) -> str:
    m = re.search(r"\+([0-9a-f]{7})", s or "")
    return m.group(1) if m else (s or "—")


def overview(items: list[tuple[Path, dict]], root: Path) -> list[str]:
    out = ["| baseline | stage | level | run | ac2 build | reference | suite commit | " + " | ".join(STATUSES) + " |",
           "|---|---|---|---|---|---|---|" + "---|" * len(STATUSES)]
    for p, b in items:
        pv = b.get("provenance") or {}
        ref = "; ".join(x for x in (f"REW {pv['rew_version']}" if pv.get("rew_version") else "",
                                    f"OSM {pv['osm_version']}" if pv.get("osm_version") else "") if x) or "—"
        s = b.get("summary") or {}
        out.append(f"| `{p.relative_to(root)}` | {b['stage']} | {_level(b)} | {pv.get('run') or '—'} | "
                   f"{_short_build(pv.get('ac2_build'))} | {ref} | {pv.get('suite_commit') or '—'} | "
                   + " | ".join(str(s.get(k, 0)) for k in STATUSES) + " |")
    return out


def matches_for(b: dict, pattern: str) -> list[tuple[str, str | None, dict]]:
    rx = re.compile(pattern)
    out = []
    for k, e in b["checks"].items():
        k2 = k.split(".", 1)[1] if "." in k else k
        m = rx.match(k2)
        if m:
            out.append((k2[m.end():], m.groupdict().get("o"), e))
    return out


def rig_table(stage: str, bs: list[dict], rows: list[tuple[str, str]]) -> list[str]:
    bs = sorted(bs, key=lambda b: -(b.get("level_dbfs") or 0.0))
    head = "| check | " + " | ".join(f"{_level(b)} ({(b.get('provenance') or {}).get('run')}, "
                                     f"{_short_build((b.get('provenance') or {}).get('ac2_build'))})" for b in bs) + " |"
    out = [head, "|---|" + "---|" * len(bs)]
    for label, pat in rows:
        cells = [cell(matches_for(b, pat)) for b in bs]
        if all(c == "—" for c in cells):
            continue
        out.append(f"| {label} | " + " | ".join(cells) + " |")
    return out


def _osm_cell(b: dict, case: str, slug) -> str:
    for s in (slug if isinstance(slug, tuple) else (slug,)):
        e = b["checks"].get(f"osm.{case}.{s}")
        if e is not None:
            v = fmt_value(e["value"], "")  # the column header carries the unit
            return v if e["status"] == "PASS" else f"{v} ({e['status']})"
    return ""


def osm_tables(b: dict) -> list[str]:
    seen = list(dict.fromkeys(k.split(".")[1] for k in b["checks"]))
    planned = ((b.get("provenance") or {}).get("flags") or {}).get("cases") or []
    cases = [c for c in planned if c in seen] + [c for c in seen if c not in planned]
    out = []
    for title, cols in (("Transfer (worst column, or the median on a rig take)", OSM_TF_COLS),
                        ("Delay (samples), noise and spectrum", OSM_OTHER_COLS)):
        rows = [[c] + [_osm_cell(b, c, s) for _, s in cols] for c in cases]
        rows = [r for r in rows if any(r[1:])]
        out += [f"**{title}**", "", "| case | " + " | ".join(h for h, _ in cols) + " |",
                "|---|" + "---|" * len(cols)]
        out += ["| " + " | ".join(r) + " |" for r in rows] + [""]
    info = [(k.split(".")[1], k.split(".", 2)[2][len(OSM_INFO_PREFIX):], e) for k, e in b["checks"].items()
            if k.split(".", 2)[2].startswith(OSM_INFO_PREFIX)]
    if info:
        out += ["**Uncompensated (INFO: the path's delay left in)**", "", "| case | check | value |", "|---|---|---|"]
        out += [f"| {c} | {OSM_INFO_LABELS.get(s, s.replace('_', ' ')).replace('|', chr(92) + '|')} | "
                f"{fmt_value(e['value'], '')} |" for c, s, e in sorted(info, key=lambda x: cases.index(x[0]))]
        out.append("")
    return out


def render(root: Path = BASELINES) -> str:
    root = Path(root)
    items = load(root)
    out = [BEGIN, "", "#### Baselines", ""] + overview(items, root) + [""]
    by_stage: dict[tuple[str, str], list[dict]] = {}
    for p, b in items:
        by_stage.setdefault((p.parent.name, b["stage"]), []).append(b)
    for (rig, stage), bs in sorted(by_stage.items(), key=lambda kv: (kv[0][0] == HOST_DIR, kv[0])):
        if rig == HOST_DIR and stage == "osm":
            for b in bs:
                pv = b.get("provenance") or {}
                out += [f"#### OSM stage ({pv.get('run')}, ac2 {_short_build(pv.get('ac2_build'))}, "
                        f"{pv.get('osm_version')})", ""] + osm_tables(b)
            continue
        rows = AMBIENT_ROWS if stage == "ambient" else RIG_ROWS
        out += [f"#### {rig} {stage}", ""] + rig_table(stage, bs, rows) + [""]
    out.append(END)
    return "\n".join(out) + "\n"


def splice(doc: str, generated: str) -> str:
    i, j = doc.find(BEGIN), doc.find(END)
    if i < 0 or j < i:
        raise ValueError(f"{DOC.name}: the marker comments are missing")
    return doc[:i] + generated + doc[j + len(END) + 1:]


def update(doc_path: Path = DOC, root: Path = BASELINES, check: bool = False) -> tuple[bool, Path]:
    """Rewrites the generated part; returns (it was current, path). `check` writes nothing."""
    doc = Path(doc_path).read_text()
    new = splice(doc, render(root))
    current = new == doc
    if not check and not current:
        Path(doc_path).write_text(new)
    return current, Path(doc_path)
